const Expense = require('../models/Expense');
const User = require('../models/User');
const Company = require('../models/Company');
const ApprovalFlow = require('../models/ApprovalFlow');
const StockItem = require('../models/StockItem');
const StockType = require('../models/StockType');
const { EXPENSE_CATEGORIES } = require('../constants/expenseCategories');
const { ensureDefaultTypes } = require('./stockTypeController');
const { convertCurrency } = require('../utils/currencyHelper');
const { sendExpenseSubmittedEmail } = require('../utils/emailService');
const Jimp = require('jimp');
const fs = require('fs');
const path = require('path');

const formatDateTime = (dateValue) => {
  if (!dateValue) return '-';
  const date = new Date(dateValue);
  if (Number.isNaN(date.getTime())) return '-';

  return date.toLocaleString('en-IN', {
    year: 'numeric',
    month: 'short',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: true
  });
};

const formatReceiptText = (expense, generatedAt = new Date()) => {
  const safeTitle = expense.title || 'Expense';
  const currency = expense.currency || 'USD';
  const amount = Number(expense.amount || 0);
  const convertedAmount = Number(expense.convertedAmount || 0);
  const companyAddressParts = [
    expense.company?.address?.street,
    expense.company?.address?.city,
    expense.company?.address?.state,
    expense.company?.address?.zipCode,
    expense.company?.address?.country || expense.company?.country
  ].filter(Boolean);
  const lines = [
    'EXPENSE RECEIPT',
    '==============================',
    `Receipt ID: REC-${expense._id.toString().slice(-10).toUpperCase()}`,
    `Generated Date & Time: ${formatDateTime(generatedAt)}`,
    `Generated UTC: ${new Date(generatedAt).toISOString()}`,
    '',
    'EXPENSE DETAILS',
    '------------------------------',
    `Title: ${safeTitle}`,
    `Description: ${expense.description || '-'}`,
    `Category: ${expense.category || '-'}`,
    `Category Type: ${expense.categoryType || '-'}`,
    `Amount: ${amount.toFixed(2)} ${currency}`,
    `Converted Amount: ${convertedAmount.toFixed(2)}`,
    `Expense Date & Time: ${formatDateTime(expense.expenseDate)}`,
    `Submitted At: ${formatDateTime(expense.createdAt)}`,
    `Status: ${expense.status || '-'}`,
    '',
    'SUBMITTED BY',
    '------------------------------',
    `Name: ${expense.user ? `${expense.user.firstName || ''} ${expense.user.lastName || ''}`.trim() : '-'}`,
    `Email: ${expense.user?.email || '-'}`,
    `Department: ${expense.user?.department || '-'}`,
    '',
    'APPROVAL',
    '------------------------------',
    `Approval Date & Time: ${formatDateTime(expense.approvalDate)}`,
    `Approved Amount: ${expense.approvedAmount ? Number(expense.approvedAmount).toFixed(2) : '-'}`,
    '',
    'COMPANY DETAILS',
    '------------------------------',
    `Company Name: ${expense.company?.name || '-'}`,
    `Company Domain: ${expense.company?.domain || '-'}`,
    `Company Email: ${expense.company?.contactEmail || '-'}`,
    `Company Phone: ${expense.company?.contactPhone || '-'}`,
    `Company Currency: ${expense.company?.currency || '-'}`,
    `Company Logo: ${expense.company?.logo || '-'}`,
    `Company Address: ${companyAddressParts.length ? companyAddressParts.join(', ') : '-'}`,
    '',
    'Generated by Expense Management System'
  ];

  return lines.join('\n');
};

const normalizeStockName = (value) => (value || '').toString().trim().toLowerCase();

const getAuthorizedExpense = async (expenseId, reqUser) => {
  const expense = await Expense.findById(expenseId)
    .populate('user', 'firstName lastName email employeeId department')
    .populate('company', 'name domain country currency logo address contactEmail contactPhone timezone')
    .populate('approvals.approver', 'firstName lastName email role');

  if (!expense) {
    return { error: { status: 404, message: 'Expense not found' } };
  }

  const canView =
    expense.user._id.toString() === reqUser.id ||
    reqUser.role === 'ADMIN' ||
    (reqUser.role === 'MANAGER' && await isUserInTeam(expense.user._id, reqUser.id)) ||
    expense.approvals.some((approval) => {
      if (!approval?.approver) return false;
      const approverId = approval.approver._id ? approval.approver._id.toString() : approval.approver.toString();
      return approverId === reqUser.id;
    });

  if (!canView) {
    return { error: { status: 403, message: 'Access denied' } };
  }

  return { expense };
};

const escapeRegex = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

const getDateRangeFilter = (startDate, endDate) => {
  if (!startDate || !endDate) return null;
  return {
    $gte: new Date(startDate),
    $lte: new Date(endDate)
  };
};

const getSortConfig = (sortBy, sortOrder) => {
  const allowedSortFields = new Set(['title', 'amount', 'expenseDate', 'status', 'createdAt']);
  const field = allowedSortFields.has(sortBy) ? sortBy : 'createdAt';
  const order = sortOrder === 'asc' ? 1 : -1;
  return { [field]: order };
};

const applyCommonExpenseFilters = (filter, query) => {
  const { status, category, startDate, endDate, search } = query;

  if (status && status !== 'ALL') {
    filter.status = status;
  }
  if (category && category !== 'ALL') {
    filter.category = category;
  }

  const dateFilter = getDateRangeFilter(startDate, endDate);
  if (dateFilter) {
    filter.expenseDate = dateFilter;
  }

  if (search && search.trim()) {
    const escaped = escapeRegex(search.trim());
    filter.$or = [
      { title: { $regex: escaped, $options: 'i' } },
      { description: { $regex: escaped, $options: 'i' } },
      { status: { $regex: escaped, $options: 'i' } },
      { category: { $regex: escaped, $options: 'i' } }
    ];
  }
};

const escapeCsv = (value) => {
  if (value === null || value === undefined) return '';
  const text = String(value).replace(/"/g, '""');
  if (/[",\n]/.test(text)) return `"${text}"`;
  return text;
};

const escapePdfText = (value) => String(value || '').replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
const truncateText = (value, max = 40) => {
  const text = String(value || '');
  if (text.length <= max) return text;
  return `${text.slice(0, Math.max(0, max - 3))}...`;
};

const resolveLocalLogoPath = (logoPath) => {
  if (!logoPath || typeof logoPath !== 'string') return null;
  if (logoPath.startsWith('http://') || logoPath.startsWith('https://')) return null;
  if (!logoPath.startsWith('/uploads/')) return null;
  return path.join(__dirname, '..', logoPath.replace('/uploads/', 'uploads/'));
};

const loadCompanyLogoData = async (logoPath) => {
  try {
    const localPath = resolveLocalLogoPath(logoPath);
    if (!localPath || !fs.existsSync(localPath)) return null;

    const image = await Jimp.read(localPath);
    image.quality(80);
    const maxWidth = 120;
    const maxHeight = 45;
    image.scaleToFit(maxWidth, maxHeight);
    const buffer = await image.getBufferAsync(Jimp.MIME_JPEG);

    return {
      buffer,
      width: image.bitmap.width,
      height: image.bitmap.height
    };
  } catch (error) {
    console.error('Load company logo for PDF error:', error);
    return null;
  }
};

const buildPdfBufferFromObjects = (objects) => {
  const header = Buffer.from('%PDF-1.4\n%\xFF\xFF\xFF\xFF\n', 'binary');
  const chunks = [header];
  const offsets = [0];
  let currentOffset = header.length;

  objects.forEach((obj, index) => {
    offsets.push(currentOffset);
    const objHeader = Buffer.from(`${index + 1} 0 obj\n`, 'utf8');
    const objBody = Buffer.isBuffer(obj) ? obj : Buffer.from(String(obj), 'utf8');
    const objFooter = Buffer.from('\nendobj\n', 'utf8');
    chunks.push(objHeader, objBody, objFooter);
    currentOffset += objHeader.length + objBody.length + objFooter.length;
  });

  const xrefOffset = currentOffset;
  let xref = `xref\n0 ${objects.length + 1}\n`;
  xref += '0000000000 65535 f \n';
  for (let i = 1; i < offsets.length; i++) {
    xref += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }

  const trailer = `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  chunks.push(Buffer.from(xref, 'utf8'), Buffer.from(trailer, 'utf8'));
  return Buffer.concat(chunks);
};

const buildStyledMonthlyReportPdf = async ({
  companyName,
  companyLogo,
  monthLabel,
  filtersLabel,
  generatedAt,
  expenses,
  totalAmount
}) => {
  const pageWidth = 612;
  const pageHeight = 792;
  const left = 36;
  const right = pageWidth - 36;
  const tableTop = 585;
  const rowHeight = 18;
  const maxRows = 20;
  const visibleRows = expenses.slice(0, maxRows);
  const hiddenCount = Math.max(0, expenses.length - visibleRows.length);

  const cols = [
    { key: 'date', label: 'Date', width: 70 },
    { key: 'title', label: 'Title', width: 165 },
    { key: 'user', label: 'Employee', width: 120 },
    { key: 'category', label: 'Category', width: 85 },
    { key: 'status', label: 'Status', width: 60 },
    { key: 'amount', label: 'Amount', width: 76 }
  ];

  const logoData = await loadCompanyLogoData(companyLogo);
  const commands = [];

  // Header background
  commands.push('0.12 0.29 0.63 rg');
  commands.push(`${left} ${pageHeight - 90} ${right - left} 54 re f`);

  // Header text
  commands.push('BT');
  commands.push('/F2 16 Tf');
  commands.push('1 1 1 rg');
  commands.push(`1 0 0 1 ${left + 12} ${pageHeight - 58} Tm`);
  commands.push(`(${escapePdfText(companyName || 'Expense Management')}) Tj`);
  commands.push('/F1 11 Tf');
  commands.push(`1 0 0 1 ${left + 12} ${pageHeight - 76} Tm`);
  commands.push('(Monthly Expense Report) Tj');
  commands.push('ET');

  if (logoData) {
    const logoX = right - 132;
    const logoY = pageHeight - 82;
    commands.push(`q ${logoData.width} 0 0 ${logoData.height} ${logoX} ${logoY} cm /Im1 Do Q`);
  } else {
    commands.push('0.9 0.9 0.9 rg');
    commands.push(`${right - 126} ${pageHeight - 82} 110 34 re f`);
    commands.push('0.4 0.4 0.4 rg');
    commands.push('BT /F1 8 Tf');
    commands.push(`1 0 0 1 ${right - 116} ${pageHeight - 66} Tm`);
    commands.push('(Company Logo) Tj');
    commands.push('ET');
  }

  // Meta block
  commands.push('0.96 0.97 0.99 rg');
  commands.push(`${left} ${pageHeight - 158} ${right - left} 56 re f`);
  commands.push('0.2 0.2 0.2 rg');
  commands.push('BT /F1 10 Tf');
  commands.push(`1 0 0 1 ${left + 10} ${pageHeight - 128} Tm`);
  commands.push(`(${escapePdfText(`Report Month: ${monthLabel}`)}) Tj`);
  commands.push(`1 0 0 1 ${left + 10} ${pageHeight - 143} Tm`);
  commands.push(`(${escapePdfText(`Filters: ${filtersLabel}`)}) Tj`);
  commands.push(`1 0 0 1 ${left + 350} ${pageHeight - 128} Tm`);
  commands.push(`(${escapePdfText(`Generated: ${formatDateTime(generatedAt)}`)}) Tj`);
  commands.push(`1 0 0 1 ${left + 350} ${pageHeight - 143} Tm`);
  commands.push(`(${escapePdfText(`Total Amount: ${totalAmount.toFixed(2)}`)}) Tj`);
  commands.push('ET');

  // Table header background
  commands.push('0.86 0.9 0.97 rg');
  commands.push(`${left} ${tableTop} ${right - left} ${rowHeight} re f`);

  // Table borders
  const tableHeight = rowHeight * (visibleRows.length + 1);
  commands.push('0.6 0.6 0.6 RG');
  commands.push('0.8 w');
  commands.push(`${left} ${tableTop - (tableHeight - rowHeight)} ${right - left} ${tableHeight} re S`);

  let xCursor = left;
  cols.forEach((col) => {
    xCursor += col.width;
    commands.push(`${xCursor} ${tableTop - (tableHeight - rowHeight)} m ${xCursor} ${tableTop + rowHeight} l S`);
  });

  for (let i = 1; i <= visibleRows.length; i++) {
    const y = tableTop - (rowHeight * i);
    commands.push(`${left} ${y} m ${right} ${y} l S`);
  }

  // Table header text
  commands.push('BT /F2 9 Tf 0.1 0.1 0.1 rg');
  xCursor = left;
  cols.forEach((col) => {
    commands.push(`1 0 0 1 ${xCursor + 4} ${tableTop + 6} Tm`);
    commands.push(`(${escapePdfText(col.label)}) Tj`);
    xCursor += col.width;
  });
  commands.push('ET');

  // Table row text
  visibleRows.forEach((expense, idx) => {
    const rowY = tableTop - (rowHeight * (idx + 1)) + 5;
    const rowValues = {
      date: new Date(expense.expenseDate).toISOString().slice(0, 10),
      title: truncateText(expense.title, 34),
      user: truncateText(`${expense.user?.firstName || ''} ${expense.user?.lastName || ''}`.trim(), 24),
      category: truncateText(expense.category, 13),
      status: truncateText(expense.status, 9),
      amount: `${Number(expense.amount || 0).toFixed(2)} ${expense.currency || ''}`
    };

    commands.push('BT /F1 8 Tf 0.15 0.15 0.15 rg');
    let cellX = left;
    cols.forEach((col) => {
      commands.push(`1 0 0 1 ${cellX + 4} ${rowY} Tm`);
      commands.push(`(${escapePdfText(rowValues[col.key])}) Tj`);
      cellX += col.width;
    });
    commands.push('ET');
  });

  if (hiddenCount > 0) {
    commands.push('BT /F1 9 Tf 0.3 0.3 0.3 rg');
    commands.push(`1 0 0 1 ${left} ${tableTop - tableHeight - 16} Tm`);
    commands.push(`(${escapePdfText(`Showing first ${visibleRows.length} rows. ${hiddenCount} additional rows not displayed in PDF.`)}) Tj`);
    commands.push('ET');
  }

  // Footer
  commands.push('0.95 0.95 0.95 rg');
  commands.push(`${left} 24 ${right - left} 24 re f`);
  commands.push('BT /F1 8 Tf 0.35 0.35 0.35 rg');
  commands.push(`1 0 0 1 ${left + 10} 33 Tm`);
  commands.push(`(${escapePdfText(`Generated by Expense Management System | ${formatDateTime(generatedAt)} | Page 1`)}) Tj`);
  commands.push('ET');

  const contentStream = commands.join('\n');
  const contentBuffer = Buffer.from(contentStream, 'utf8');

  let contentObjNumber = 5;
  let imageObj = null;
  let resources = '/Font << /F1 4 0 R /F2 6 0 R >>';

  if (logoData) {
    imageObj = Buffer.concat([
      Buffer.from(`<< /Type /XObject /Subtype /Image /Width ${logoData.width} /Height ${logoData.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${logoData.buffer.length} >>\nstream\n`, 'utf8'),
      logoData.buffer,
      Buffer.from('\nendstream', 'utf8')
    ]);
    resources += ' /XObject << /Im1 7 0 R >>';
  }

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << ${resources} >> /Contents ${contentObjNumber} 0 R >>`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${contentBuffer.length} >>\nstream\n${contentStream}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'
  ];

  if (imageObj) {
    objects.push(imageObj);
  }

  return buildPdfBufferFromObjects(objects);
};

const getManagerTeamUserIds = async (managerId, companyId) => {
  const teamMembers = await User.find({
    company: companyId,
    manager: managerId
  }).select('_id');

  const teamMemberIds = teamMembers.map((member) => member._id.toString());
  teamMemberIds.push(managerId.toString());
  return teamMemberIds;
};

// Create new expense
const createExpense = async (req, res) => {
  try {
    const {
      title,
      description,
      amount,
      currency,
      category,
      categoryType,
      expenseDate,
      ocrData,
      transportMode,
      transportCompany
    } = req.body;

    // Validate payload early to avoid generic 500 errors
    if (!title || !description || !amount || !currency || !category || !expenseDate) {
      return res.status(400).json({ message: 'Please provide all required expense fields' });
    }

    const numericAmount = Number(amount);
    if (!Number.isFinite(numericAmount) || numericAmount <= 0) {
      return res.status(400).json({ message: 'Amount must be a valid number greater than 0' });
    }

    const parsedExpenseDate = new Date(expenseDate);
    if (Number.isNaN(parsedExpenseDate.getTime())) {
      return res.status(400).json({ message: 'Expense date is invalid' });
    }

    // Convert amount to company currency if different
    const user = await User.findById(req.user.id).populate('company');
    if (!user || !user.company) {
      return res.status(400).json({ message: 'User company information is missing' });
    }

    // If stock already exists and is full/blocked, do not allow submitting a new request.
    // (Stocks quantity increments only on final approval, but maxQuantity still indicates capacity.)
    const submittedStockName = (title || '').toString().trim();
    const submittedNameNormalized = normalizeStockName(submittedStockName);
    if (submittedNameNormalized) {
      const existingStock = await StockItem.findOne({
        company: req.user.company,
        nameNormalized: submittedNameNormalized
      }).select('name status quantity maxQuantity');

      if (existingStock && existingStock.status === 'BLOCKED') {
        return res.status(400).json({
          message: `Stock is blocked for "${existingStock.name}". Cannot submit this request.`
        });
      }

      if (existingStock && existingStock.maxQuantity > 0 && existingStock.quantity >= existingStock.maxQuantity) {
        return res.status(400).json({
          message: `Stock is full for "${existingStock.name}". Cannot submit this request.`
        });
      }
    }

    let convertedAmount = numericAmount;

    if (currency !== user.company.currency) {
      convertedAmount = await convertCurrency(numericAmount, currency, user.company.currency);
    }

    let parsedOcrData = null;
    if (ocrData) {
      if (typeof ocrData === 'string') {
        try {
          parsedOcrData = JSON.parse(ocrData);
        } catch (parseError) {
          return res.status(400).json({ message: 'OCR data format is invalid' });
        }
      } else {
        parsedOcrData = ocrData;
      }
    }

    // Create expense
    const expense = new Expense({
      user: req.user.id,
      company: req.user.company,
      title,
      description,
      amount: numericAmount,
      currency,
      convertedAmount,
      category,
      categoryType: category === 'TRANSPORT'
        ? ((transportMode || categoryType || '').toString().trim())
        : ((categoryType || '').toString().trim()),
      expenseDate: parsedExpenseDate,
      receipts: [],
      ocrData: parsedOcrData,
      transportDetails: category === 'TRANSPORT' ? {
        mode: transportMode || undefined,
        company: (transportCompany || '').toString().trim()
      } : undefined
    });

    // Handle file uploads
    if (req.files && req.files.length > 0) {
      expense.receipts = req.files.map(file => ({
        filename: file.filename,
        originalName: file.originalname,
        path: file.path,
        size: file.size,
        mimetype: file.mimetype
      }));
    }

    await expense.save();

    // Ensure requested item/product exists in Stocks list for the company.
    // Do not change quantity here (quantity changes on final approval).
    try {
      const stockName = (expense.title || '').toString().trim();
      const nameNormalized = normalizeStockName(stockName);
      if (nameNormalized) {
        // Ensure baseline types exist (expense categories).
        await ensureDefaultTypes(req.user.company);

        // Try to match typeId from category stock type (if present).
        const categoryName = (category || 'OTHER').toString().trim();
        const categoryType = await StockType.findOne({
          company: req.user.company,
          nameNormalized: normalizeStockName(categoryName)
        }).select('_id name group');

        await StockItem.findOneAndUpdate(
          { company: req.user.company, nameNormalized },
          {
            $setOnInsert: {
              company: req.user.company,
              name: stockName,
              nameNormalized,
              quantity: 0,
              maxQuantity: 0,
              typeId: categoryType?._id || null,
              type: categoryType?.name || categoryName || 'OTHER',
              typeGroup: categoryType?.group || categoryName || 'OTHER',
              status: 'ACTIVE'
            }
          },
          { upsert: true, new: false, setDefaultsOnInsert: true }
        );
      }

      // Add all expense categories to Stocks (as stock items with quantity 0 by default).
      // This keeps Stocks list complete even before any category is used.
      await Promise.all(
        (EXPENSE_CATEGORIES || []).map(async (cat) => {
          const catName = (cat || '').toString().trim();
          const catNormalized = normalizeStockName(catName);
          if (!catNormalized) return;
          await StockItem.findOneAndUpdate(
            { company: req.user.company, nameNormalized: catNormalized },
            {
              $setOnInsert: {
                company: req.user.company,
                name: catName,
                nameNormalized: catNormalized,
                quantity: 0,
                maxQuantity: 0,
                typeId: null,
                type: catName,
                typeGroup: catName,
                status: 'ACTIVE'
              }
            },
            { upsert: true, new: false, setDefaultsOnInsert: true }
          );
        })
      );
    } catch (stockError) {
      console.error('Stock upsert on expense create error:', stockError);
      // Do not block expense creation if stock list update fails.
    }

    // Start approval workflow
    try {
      await startApprovalWorkflow(expense);
    } catch (workflowError) {
      console.error('Approval workflow error:', workflowError);
      // Continue even if approval workflow fails
    }

    await expense.populate([
      { path: 'user', select: 'firstName lastName email' },
      { path: 'approvals.approver', select: 'firstName lastName email' }
    ]);

    if (user.preferences?.emailNotifications !== false) {
      sendExpenseSubmittedEmail({
        to: user.email,
        userName: `${user.firstName} ${user.lastName}`.trim(),
        expenseTitle: expense.title,
        amount: Number(expense.amount).toFixed(2),
        currency: expense.currency,
        expenseDate: formatDateTime(expense.expenseDate),
        status: expense.status
      }).catch((emailError) => {
        console.error('Expense submission email error:', emailError);
      });
    }

    res.status(201).json({
      message: 'Expense created successfully',
      expense
    });
  } catch (error) {
    console.error('Create expense error:', error);
    console.error('Error details:', error.message);
    console.error('Stack trace:', error.stack);
    res.status(500).json({ 
      message: 'Server error',
      error: process.env.NODE_ENV === 'development' ? error.message : 'Internal server error'
    });
  }
};

// Get user expenses
const getUserExpenses = async (req, res) => {
  try {
    const { sortBy, sortOrder } = req.query;
    const page = Math.max(parseInt(req.query.page, 10) || 1, 1);
    const limit = Math.max(parseInt(req.query.limit, 10) || 10, 1);

    const filter = { user: req.user.id };
    applyCommonExpenseFilters(filter, req.query);

    const sort = getSortConfig(sortBy, sortOrder);

    const expenses = await Expense.find(filter)
      .populate('approvals.approver', 'firstName lastName email')
      .sort(sort)
      .limit(limit)
      .skip((page - 1) * limit);

    const total = await Expense.countDocuments(filter);

    res.json({
      expenses,
      totalPages: Math.ceil(total / limit),
      currentPage: page,
      totalExpenses: total
    });
  } catch (error) {
    console.error('Get user expenses error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// Get all company expenses (Admin/Manager)
const getCompanyExpenses = async (req, res) => {
  try {
    const { userId, sortBy, sortOrder } = req.query;
    const page = Math.max(parseInt(req.query.page, 10) || 1, 1);
    const limit = Math.max(parseInt(req.query.limit, 10) || 10, 1);

    const filter = { company: req.user.company };
    applyCommonExpenseFilters(filter, req.query);

    if (userId && userId !== 'ALL') {
      filter.user = userId;
    }

    // For managers, show only their team's expenses
    if (req.user.role === 'MANAGER') {
      const teamMemberIds = await getManagerTeamUserIds(req.user.id, req.user.company);
      if (userId && userId !== 'ALL') {
        if (!teamMemberIds.includes(userId.toString())) {
          return res.status(403).json({ message: 'Access denied for selected user' });
        }
        filter.user = userId;
      } else {
        filter.user = { $in: teamMemberIds };
      }
    }

    const sort = getSortConfig(sortBy, sortOrder);
    const expenses = await Expense.find(filter)
      .populate('user', 'firstName lastName email employeeId department')
      .populate('approvals.approver', 'firstName lastName email')
      .sort(sort)
      .limit(limit)
      .skip((page - 1) * limit);

    const total = await Expense.countDocuments(filter);

    res.json({
      expenses,
      totalPages: Math.ceil(total / limit),
      currentPage: page,
      totalExpenses: total
    });
  } catch (error) {
    console.error('Get company expenses error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// Get single expense
const getExpense = async (req, res) => {
  try {
    const { expenseId } = req.params;

    const expense = await Expense.findById(expenseId)
      .populate('user', 'firstName lastName email employeeId department')
      .populate('company', 'name domain country currency logo address contactEmail contactPhone timezone')
      .populate('approvals.approver', 'firstName lastName email role');

    if (!expense) {
      return res.status(404).json({ message: 'Expense not found' });
    }

    // Check if user has permission to view this expense
    const canView = 
      expense.user._id.toString() === req.user.id || // Own expense
      req.user.role === 'ADMIN' || // Admin can view all
      (req.user.role === 'MANAGER' && await isUserInTeam(expense.user._id, req.user.id)) || // Manager can view team expenses
      expense.approvals.some((approval) => {
        if (!approval?.approver) return false;
        const approverId = approval.approver._id ? approval.approver._id.toString() : approval.approver.toString();
        return approverId === req.user.id;
      }); // Approver can view

    if (!canView) {
      return res.status(403).json({ message: 'Access denied' });
    }

    res.json({ expense });
  } catch (error) {
    console.error('Get expense error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// Get generated receipt preview for a single expense
const getExpenseReceipt = async (req, res) => {
  try {
    const { expenseId } = req.params;
    const result = await getAuthorizedExpense(expenseId, req.user);

    if (result.error) {
      return res.status(result.error.status).json({ message: result.error.message });
    }

    const generatedAt = new Date();
    const receiptContent = formatReceiptText(result.expense, generatedAt);

    return res.json({
      receipt: {
        expenseId,
        generatedAt,
        content: receiptContent
      }
    });
  } catch (error) {
    console.error('Get receipt error:', error);
    return res.status(500).json({ message: 'Server error' });
  }
};

// Export monthly report as CSV or PDF
const exportMonthlyReport = async (req, res) => {
  try {
    const { month, year, format = 'csv', userId } = req.query;
    const status = req.query.status || 'ALL';
    const category = req.query.category || 'ALL';

    const targetDate = new Date();
    const targetMonth = Number.isFinite(Number(month)) ? Number(month) : targetDate.getMonth() + 1;
    const targetYear = Number.isFinite(Number(year)) ? Number(year) : targetDate.getFullYear();

    if (targetMonth < 1 || targetMonth > 12) {
      return res.status(400).json({ message: 'Month must be between 1 and 12' });
    }
    if (!['csv', 'pdf'].includes(format.toLowerCase())) {
      return res.status(400).json({ message: 'Format must be csv or pdf' });
    }

    const fromDate = new Date(targetYear, targetMonth - 1, 1);
    const toDate = new Date(targetYear, targetMonth, 0, 23, 59, 59, 999);
    const filter = { expenseDate: { $gte: fromDate, $lte: toDate } };

    if (status !== 'ALL') filter.status = status;
    if (category !== 'ALL') filter.category = category;

    if (req.user.role === 'EMPLOYEE') {
      filter.user = req.user.id;
    } else if (req.user.role === 'MANAGER') {
      const teamUserIds = await getManagerTeamUserIds(req.user.id, req.user.company);
      filter.company = req.user.company;
      if (userId && userId !== 'ALL') {
        if (!teamUserIds.includes(userId.toString())) {
          return res.status(403).json({ message: 'Access denied for selected user' });
        }
        filter.user = userId;
      } else {
        filter.user = { $in: teamUserIds };
      }
    } else {
      filter.company = req.user.company;
      if (userId && userId !== 'ALL') filter.user = userId;
    }

    const expenses = await Expense.find(filter)
      .populate('user', 'firstName lastName email')
      .sort({ expenseDate: 1 });
    const company = await Company.findById(req.user.company).select('name logo');

    const monthLabel = new Date(targetYear, targetMonth - 1, 1).toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
    const totalAmount = expenses.reduce((sum, expense) => sum + Number(expense.convertedAmount || 0), 0);

    if (format.toLowerCase() === 'csv') {
      const header = ['Date', 'Title', 'Description', 'Amount', 'Currency', 'ConvertedAmount', 'Category', 'Status', 'Employee'];
      const rows = expenses.map((expense) => [
        new Date(expense.expenseDate).toISOString().slice(0, 10),
        expense.title,
        expense.description,
        Number(expense.amount || 0).toFixed(2),
        expense.currency,
        Number(expense.convertedAmount || 0).toFixed(2),
        expense.category,
        expense.status,
        `${expense.user?.firstName || ''} ${expense.user?.lastName || ''}`.trim()
      ]);

      const csv = [header, ...rows].map((row) => row.map(escapeCsv).join(',')).join('\n');
      const fileName = `monthly-expense-report-${targetYear}-${String(targetMonth).padStart(2, '0')}.csv`;

      res.setHeader('Content-Type', 'text/csv; charset=utf-8');
      res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
      return res.send(csv);
    }

    const filtersLabel = `Status=${status}, Category=${category}, User=${userId || 'ALL'}, Records=${expenses.length}`;
    const pdfBuffer = await buildStyledMonthlyReportPdf({
      companyName: company?.name || 'Expense Management',
      companyLogo: company?.logo || '',
      monthLabel,
      filtersLabel,
      generatedAt: new Date(),
      expenses,
      totalAmount
    });
    const fileName = `monthly-expense-report-${targetYear}-${String(targetMonth).padStart(2, '0')}.pdf`;
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
    return res.send(pdfBuffer);
  } catch (error) {
    console.error('Export monthly report error:', error);
    return res.status(500).json({ message: 'Server error' });
  }
};

// Download generated receipt for a single expense
const downloadExpenseReceipt = async (req, res) => {
  try {
    const { expenseId } = req.params;
    const result = await getAuthorizedExpense(expenseId, req.user);

    if (result.error) {
      return res.status(result.error.status).json({ message: result.error.message });
    }

    const generatedAt = new Date();
    const receiptText = formatReceiptText(result.expense, generatedAt);
    const safeTitle = (result.expense.title || 'expense')
      .replace(/[^a-zA-Z0-9-_]/g, '_')
      .toLowerCase();
    const fileName = `receipt-${safeTitle}-${result.expense._id.toString().slice(-6)}.txt`;

    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
    return res.send(receiptText);
  } catch (error) {
    console.error('Download receipt error:', error);
    return res.status(500).json({ message: 'Server error' });
  }
};

// Update expense (only if pending)
const updateExpense = async (req, res) => {
  try {
    const { expenseId } = req.params;
    const {
      title,
      description,
      amount,
      currency,
      category,
      categoryType,
      expenseDate,
      transportMode,
      transportCompany
    } = req.body;

    const expense = await Expense.findOne({ 
      _id: expenseId, 
      user: req.user.id 
    });

    if (!expense) {
      return res.status(404).json({ message: 'Expense not found' });
    }

    if (expense.status !== 'PENDING' && expense.status !== 'DRAFT') {
      return res.status(400).json({ message: 'Cannot edit expense after approval process has started' });
    }

    // Prevent updates that would target a blocked/full stock item.
    const nextTitle = (title !== undefined ? title : expense.title) || '';
    const nextNameNormalized = normalizeStockName(nextTitle.toString().trim());
    if (nextNameNormalized) {
      const existingStock = await StockItem.findOne({
        company: req.user.company,
        nameNormalized: nextNameNormalized
      }).select('name status quantity maxQuantity');

      if (existingStock && existingStock.status === 'BLOCKED') {
        return res.status(400).json({
          message: `Stock is blocked for "${existingStock.name}". Cannot update this request.`
        });
      }

      if (existingStock && existingStock.maxQuantity > 0 && existingStock.quantity >= existingStock.maxQuantity) {
        return res.status(400).json({
          message: `Stock is full for "${existingStock.name}". Cannot update this request.`
        });
      }
    }

    // Convert amount if currency changed
    const user = await User.findById(req.user.id).populate('company');
    const numericAmount = amount !== undefined ? Number(amount) : expense.amount;
    if (!Number.isFinite(numericAmount) || numericAmount <= 0) {
      return res.status(400).json({ message: 'Amount must be a valid number greater than 0' });
    }

    let convertedAmount = numericAmount;

    if (currency && currency !== user.company.currency) {
      convertedAmount = await convertCurrency(numericAmount, currency, user.company.currency);
    }

    const nextCategory = category || expense.category;
    const categoryChanged = Boolean(category) && category !== expense.category;

    let nextCategoryType = expense.categoryType || '';
    if (categoryType !== undefined) {
      nextCategoryType = (categoryType || '').toString().trim();
    } else if (categoryChanged) {
      nextCategoryType = '';
    }

    // Update expense
    expense.title = title || expense.title;
    expense.description = description || expense.description;
    expense.amount = numericAmount;
    expense.currency = currency || expense.currency;
    expense.convertedAmount = convertedAmount;
    expense.category = nextCategory;

    if (nextCategory === 'TRANSPORT') {
      const modeValue = (transportMode || '').toString().trim();
      const companyValue = (transportCompany || '').toString().trim();
      expense.transportDetails = {
        mode: modeValue || undefined,
        company: companyValue
      };
      expense.categoryType = modeValue || nextCategoryType || '';
    } else {
      expense.transportDetails = undefined;
      expense.categoryType = nextCategoryType;
    }
    if (expenseDate) {
      const parsedUpdateDate = new Date(expenseDate);
      if (Number.isNaN(parsedUpdateDate.getTime())) {
        return res.status(400).json({ message: 'Expense date is invalid' });
      }
      expense.expenseDate = parsedUpdateDate;
    }

    // Handle new file uploads
    if (req.files && req.files.length > 0) {
      const newReceipts = req.files.map(file => ({
        filename: file.filename,
        originalName: file.originalname,
        path: file.path,
        size: file.size,
        mimetype: file.mimetype
      }));
      expense.receipts = [...expense.receipts, ...newReceipts];
    }

    await expense.save();

    res.json({
      message: 'Expense updated successfully',
      expense
    });
  } catch (error) {
    console.error('Update expense error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// Delete expense (only if pending)
const deleteExpense = async (req, res) => {
  try {
    const { expenseId } = req.params;

    const expense = await Expense.findOne({ 
      _id: expenseId, 
      user: req.user.id 
    });

    if (!expense) {
      return res.status(404).json({ message: 'Expense not found' });
    }

    if (expense.status !== 'PENDING' && expense.status !== 'DRAFT') {
      return res.status(400).json({ message: 'Cannot delete expense after approval process has started' });
    }

    await Expense.findByIdAndDelete(expenseId);

    res.json({ message: 'Expense deleted successfully' });
  } catch (error) {
    console.error('Delete expense error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// Helper function to start approval workflow
const startApprovalWorkflow = async (expense) => {
  try {
    // Get default approval flow for the company
    const approvalFlow = await ApprovalFlow.findOne({
      company: expense.company,
      isActive: true,
      isDefault: true
    }).populate('steps.approvers');

    if (!approvalFlow) {
      // If no approval flow, set to pending for manual review
      expense.status = 'PENDING';
      await expense.save();
      return;
    }

    expense.approvalFlow = approvalFlow._id;
    expense.currentApprovalStep = 0;

    // Create approval entries for each step
    for (let i = 0; i < approvalFlow.steps.length; i++) {
      const step = approvalFlow.steps[i];

      let approvers = [];

      if (step.approverType === 'MANAGER') {
        // Get user's manager
        const user = await User.findById(expense.user).populate('manager');
        if (user && user.manager) {
          approvers = [user.manager._id];
        }
      } else if (step.approverType === 'SPECIFIC_USER' && step.approvers) {
        approvers = step.approvers.map(approver => approver._id);
      }

      // Only add approvals if we have approvers
      if (approvers.length > 0) {
        for (const approverId of approvers) {
          expense.approvals.push({
            approver: approverId,
            stepNumber: i,
            status: 'PENDING'
          });
        }
      }
    }

    // If no approvals were created, set to pending
    if (expense.approvals.length === 0) {
      expense.status = 'PENDING';
    }

    await expense.save();
  } catch (error) {
    console.error('Start approval workflow error:', error);
    // Set to pending if workflow fails
    expense.status = 'PENDING';
    await expense.save();
  }
};

// Helper function to check if user is in team
const isUserInTeam = async (userId, managerId) => {
  const user = await User.findById(userId);
  return user && user.manager && user.manager.toString() === managerId;
};

module.exports = {
  createExpense,
  getUserExpenses,
  getCompanyExpenses,
  exportMonthlyReport,
  getExpense,
  getExpenseReceipt,
  downloadExpenseReceipt,
  updateExpense,
  deleteExpense
};
